apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whatsit-image-index
  namespace: whatsit
spec:
  replicas:
  template:
    metadata:
      labels:
        role: whatsit-image-index
        name: whatsit-image-index
    spec:
      containers:
      - image: gcr.io/whatsit-174908/whatsit-image-index:latest
        name: whatsit-image-index
        env:
        - name: PROJECTID
          value: whatsit-174908
        ports:
        - containerPort: 6379